services:
  server:
    env_file: .env
    container_name: bia
    image: 654654321982.dkr.ecr.us-east-1.amazonaws.com/bia:571001d
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
